spring:
  profiles:
    active: 
  application:
    name: okta-demo-app
  cloud:
    config:
      uri: http://localhost:8888
      label: master
      
logging:
  level:
    root: INFO
    # org.springframework.cloud: 'DEBUG'